# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/customer-sales-repo/frontend:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/customer-sales-repo/frontend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/customer-sales-repo/frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/customer-sales-repo/frontend:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/customer-sales-repo/frontend:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/customer-sales-repo/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY 

substitutions:
  _REGION: 'us-central1'